name: deploy to gcloud

on:
  push:
    branches: [master]

jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            cmd:
              - 'filtertest/**'

      - name: "echo"
        shell: bash
        run: ./ci/deploy.sh ${{ steps.filter.outputs.cmd_list }}

      - name: "echo2"
        shell: bash
        if: ${{ steps.filter.outputs.cmd }}
        run: |
          echo ${outputs.cmd}
