name: deploy to gcloud

on:
  push:
    branches: [master]

jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Setup Path Filter task and Execute
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            cmd:
              - 'filtertest/**'

      - name: "echo"
        shell: bash
        run: |
          for c_d in ${{ steps.filter.outputs.cmd_files }}; do
            echo ${c_d}
          done
